name: 'Dynamic Badges'
description: 'Creates badge descriptions to be used with shields.io/endpoint and uploads them to a gist.'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  auth:
    description: 'Your secret with the gist scope'
    required: true
  gistID:
    description: 'The ID of the gist to use'
    required: true
  filename:
    description: 'The *.json filename of the badge data'
    required: true
  label:
    description: 'The left text of the badge'
    required: true
  message:
    description: 'The right text of the badge'
    required: true
  labelColor:
    description: 'The left color of the badge'
    required: false
  color:
    description: 'The right color of the badge'
    required: false
  isError:
    description: 'The color will be red and cannot be overridden'
    required: false
  namedLogo:
    description: 'A logo name from simpleicons.org'
    required: false
  logoSvg:
    description: 'An svg-string to be used as logo'
    required: false
  logoColor:
    description: 'The color for the logo'
    required: false
  logoWidth:
    description: 'The space allocated for the logo'
    required: false
  logoPosition:
    description: 'The position of the logo'
    required: false
  style:
    description: 'The style like "flat" or "social"'
    required: false
  cacheSeconds:
    description: 'The cache lifetime in seconds (must be greater than 300)'
    required: false
  valColorRange:
    description: 'A numerical value used to define the message color. Usually this should be between maxColorRange and minColorRange.'
    required: false
  maxColorRange:
    description: 'If valColorRange assumes this value, the badge will be green.'
    required: false
  minColorRange:
    description: 'If valColorRange assumes this value, the badge will be red.'
    required: false
  invertColorRange:
    description: 'If the range should be inverted, causing a smaller value to have green color.'
    required: false
  colorRangeSaturation:
    description: 'Saturation used by the color range feature. Defaults to 100.'
    required: false
  colorRangeLightness:
    description: 'Lightness used by the color range feature. Defaults to 40.'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
